// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-1KKmlbVv5JLC0tLTDXqr5aCwjXjPKzA',
    appId: '1:529131326843:web:ba3767103e74de8a5fc1de',
    messagingSenderId: '529131326843',
    projectId: 'bucketlistwithfirebase-64976',
    authDomain: 'bucketlistwithfirebase-64976.firebaseapp.com',
    storageBucket: 'bucketlistwithfirebase-64976.appspot.com',
    measurementId: 'G-KG0BQ4808E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQCL6llIvT6r6TdBSOObd1olQHVwK6t_k',
    appId: '1:529131326843:android:cc3b9b98df8eee105fc1de',
    messagingSenderId: '529131326843',
    projectId: 'bucketlistwithfirebase-64976',
    storageBucket: 'bucketlistwithfirebase-64976.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqcCKWjjmVi60GvUKHySE_k2BcZ84GKow',
    appId: '1:529131326843:ios:4bd101f66b0b5e2b5fc1de',
    messagingSenderId: '529131326843',
    projectId: 'bucketlistwithfirebase-64976',
    storageBucket: 'bucketlistwithfirebase-64976.appspot.com',
    iosBundleId: 'com.0929.ooi.flutterWorkspace',
  );
}
